profile_model:
  data_path: "./data/profile_model"       # Directory that contains input data
  output_path: "./results/profile_model"  # Directory to write output data
  index_label: "congener"                 # Name of the index column in CSV files
  result_column: "output"                 # Name of the column to write the results
  devices:
    - name: "ESP"              # Name of the air pollution control device (APCD)
      partition: True          # Whether or not to consider phase partitioning        
      temperature: 563.15      # Temperature of the simulated APCD, K
      ref_temperature: 507.15  # Temperature of the reference APCD, K
      conc_in: 58.966          # Inlet concentration of total PCDD/Fs
      conc_out: 134.08         # Outlet concentration of total PCDD/Fs
      adjust:                  # If included, apply adjustment factors to removal efficiencies
        phase: ["particulate"] # One or more of ["gas", "particulate", "total"]
        factors_path: "./data/profile_model/1_factors.csv" # Path to the adjustment factors
    - name: "WS"
      partition: False

quantity_model:
  data_path: "./data/quantity_model"      # Directory that contains input data
  output_path: "./results/quantity_model" # Directory to write output data
  index_label: "year"                     # Name of the index column in CSV files
  result_column: "output"                 # Name of the column to write the results
  combustion_temperature: 1223.15         # Furnace combustion temperature, K
  residence_time: 2                       # Flue gas residence time in the furnace, s
  yearly_operation_hours: 8050            # Yearly operation hours of the furnace, hours
  congener: "OCDF"                        # Name of congener for quantity estimation, one of ["2,3,7,8-TCDF", "OCDF", "1,2,3,6,7,8-HxCDD"]
  congener_fraction: 0.207                # Fraction of selected congener in total PCDD/Fs before APCDs
  removal_efficiencies: [-1.61, 0.4]      # Removal efficiencies of APCDs, [] if no APCDs