profile_model: 
  - name: "ESP"
    mode: 1
    temperature: 563.15
    ref_temperature: 507.15
    conc_in: 58.966
    conc_out: 134.08
    adjustment:
      phase: ["particulate"]
      factors_path: "./params/esp_adjust_factors.csv"
  - name: "WS"
    mode: 2

quantity_model:
  combustion_temperature: 1223.15
  residence_time: 2
  yearly_operation_hours: 8050
  ocdf_fraction: 0.207
  removal_efficiencies: [-1.61, 0.4]